include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - **/*.reflectable.*

linter:
  rules:
    omit_local_variable_types: false # I believe types in code help code comprehension
