include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - example/readme_example.reflectable.dart

linter:
  rules:
    omit_local_variable_types: false # I believe types in code help code comprehension
